### ISSUE TITLE
[FATAL] (cmd/sips/sips.go:119) open database: open database: timeout

### ISSUE THREAD

**Issue by whiteowl3** [DeedleFake/sips#15]
No matter what the permissions, where the volume is located, or how the docker is launched, every single sips and/or sipsctl command yields:
[FATAL] (cmd/sips/sips.go:119) open database: open database: timeout
Do you have a recommendation?

**Comment by whiteowl3** [comment]
same errors when built natively.

**Comment by whiteowl3** [comment]
so, i did get all the way through user and token generation on the natively built app by passing "-db /absolute/path/to/database.db" to sips on launch.
cannot get this far with docker though, even with equivalent args.

**Comment by DeedleFake** [comment]
The timeout when opening the database is only used for `flock()`. As per #9, the issue with BoltDB's locking mechanism is that the database can't be opened by both `sips` and `sipsctl` simultaneously, or by multiple instances of one of them, either. Is the database already in use by something else?

**Comment by whiteowl3** [comment]
'''
sips:
    image: sips/sips:latest
    container_name: sips
    user: "1000:1000"
    environment:
      - XDG_CONFIG_HOME=/data
      - PATH=/
    user: "1000:1000"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    command: ["sips", "-db", "/data/sips/database.db", "-api", "http://ipfs:5001"]
''
in compose, sipsctl always fails with timeout.  i have verified that sips inside the container will create the database within the mounted volume, but then nothing gets sipsctl to work inside the container. it times out no matter what, even if explicitly passed the path of the database.
any input is much appreciated.

**Comment by DeedleFake** [comment]
It looks like it's because of #9. `sips` can't be running when `sipsctl` is run, as they both require exclusive database access. I'm working on a solution, but until then the only way around it is to stop `sips` in order to run `sipsctl`. Not ideal, I know.

**Comment by DeedleFake** [comment]
This was supposed to have been closed by the above references pull request, but for some reason it didn't close it automatically, so I'm just going to do that manually here.
